# Generated by Django 5.1.6 on 2025-03-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_gemini2_delete_gemini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemini2',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
